wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.1
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1703293759.105264
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 16
      - 24
      4: 3.10.13
      5: 0.16.1
      8:
      - 2
      - 5
      13: linux-x86_64
