wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.35.2
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1703290421.627943
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 23
      4: 3.10.13
      5: 0.16.1
      6: 4.35.2
      8:
      - 1
      - 2
      - 5
      13: linux-x86_64
